version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  backend:
    build: .
    container_name: fastapi-backend
    environment:
      OPENSEARCH_HOST: "opensearch"
      OPENSEARCH_PORT: 9200
      RECOGNIZE_SPEECH_HOST: "recognize-speech"
      RECOGNIZE_SPEECH_PORT: 6000
    depends_on:
      - opensearch
      - recognize-speech
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

  recognize-speech:
    build:
      context: ./recognize-speech-service
      dockerfile: Dockerfile
    container_name: recognize-speech
    environment:
      - LANGUAGES=ru-RU,en-US
    ports:
      - "6000:6000"
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://fastapi-backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: opensearch-network

volumes:
  opensearch-data:
#version: '3.8'
#
#services:
#  opensearch:
#    image: opensearchproject/opensearch:2.6.0
#    container_name: opensearch
#    environment:
#      - discovery.type=single-node
#      - plugins.security.disabled=true
#      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - opensearch-data:/usr/share/opensearch/data
#    ports:
#      - "9200:9200"
#      - "9600:9600"
#
#  backend:
#    build: .
#    container_name: fastapi-backend
#    environment:
#      OPENSEARCH_HOST: "opensearch"
#      OPENSEARCH_PORT: 9200
#      RECOGNIZE_SPEECH_HOST: "recognize-speech"
#      RECOGNIZE_SPEECH_PORT: 6000
#    depends_on:
#      - opensearch
#      - recognize-speech
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    restart: always
#
#  recognize-speech:
#    build:
#      context: ./recognize-speech-service
#      dockerfile: Dockerfile
#    container_name: recognize-speech
#    environment:
#      - LANGUAGES=ru-RU,en-US
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
#    restart: always
#
#  frontend:
#    build: ./frontend
#    container_name: react-frontend
#    environment:
#      - REACT_APP_BACKEND_URL=http://fastapi-backend:8000
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#    restart: always
#
#networks:
#  default:
#    name: opensearch-network
#
#volumes:
#  opensearch-data:
